@host = http://localhost:4004/odata/v4/airport

### GET list of all airports along with region appended 
GET {{host}}/Airports

### Sort by name in asecending order
GET {{host}}/Airports?$orderby=name asc

### Sort by name in descending order
GET {{host}}/Airports?$orderby=name desc

### Sort by city in asecending order
GET {{host}}/Airports?$orderby=city asc

### Sort by city in descending order
GET {{host}}/Airports?$orderby=city desc


### Sort by state in asecending order
GET {{host}}/Airports?$orderby=state asc

### Sort by state in descending order
GET {{host}}/Airports?$orderby=state desc

### Sort by country in asecending order
GET {{host}}/Airports?$orderby=country asc

### Sort by country in descending order
GET {{host}}/Airports?$orderby=country desc

### Sort by elevation in descending order
GET {{host}}/Airports?$orderby=elevation desc

### Post a new airport
POST {{host}}/Airports
Content-Type: application/json

{
    "icao": "abcde",
    "iata": "Test State",
    "name": "Test Country",
    "city": "Test City",
    "state": "Test State",
    "country": "Test Country",
    "elevation": 0,
    "lat": 0,
    "lon": 0,
    "tz": "Test Timezone"
}

//Scripts

### Check avge elevation of all airports grouped by country using $apply
GET {{host}}/Airports?$apply=groupby((country), aggregate(elevation with average as avgElevation))&$orderby=avgElevation desc

### Find airports without IATA code
GET {{host}}/Airports?$filter=iata eq null

### Determine 10 most common timezones
GET {{host}}/Airports?$apply=groupby((tz), aggregate($count as count))&$orderby=count desc&$top=10


